joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 125

robot_controller:
  type: position_controllers/JointTrajectoryController

  joints: 
  - J1
  - J2
  - J3
  - J4
  - J5
  - J6

  # gains:
  #   joint_1: {p: 1000, d: 30, i: 1, i_clamp: 0}
  #   joint_2: {p: 1000, d: 30, i: 1, i_clamp: 0}
  #   joint_3: {p: 1000, d: 30, i: 1, i_clamp: 0}
  #   joint_4: {p: 1000, d: 30, i: 1, i_clamp: 0}
  #   joint_5: {p: 1000, d: 30, i: 1, i_clamp: 0}
  #   joint_6: {p: 1000, d: 30, i: 1, i_clamp: 0}
  #   joint_7: {p: 1000, d: 30, i: 1, i_clamp: 0}

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    J1: {trajectory: 0.2, goal: 0.1}
    J2: {trajectory: 0.2, goal: 0.1}
    J3: {trajectory: 0.2, goal: 0.1}
    J4: {trajectory: 0.2, goal: 0.1}
    J5: {trajectory: 0.2, goal: 0.1}
    J6: {trajectory: 0.2, goal: 0.1}

  stop_trajectory_duration: 0.5
  state_publish_rate: 125
  action_monitor_rate: 20

gripper_controller:
  type: effort_controllers/JointGroupPositionController
  joints: 
    - finger1_joint
    - finger2_joint

  finger1_joint: 
    pid: {p: 1000.0, i: 10.0, d: 100.0}
  finger2_joint: 
    pid: {p: 1000.0, i: 10.0, d: 100.0}
